### ISSUE TITLE
A problem with 'project.undelete()'.

### ISSUE THREAD

**Issue by iMrDJAi** [NintendoZaedus/glitch.js#1]
```js
var project = ((await me.getProjects()).filter(project => project.domain === 'some-name'))[0];
project.delete();
setTimeout(() => project.undelete(), 2000); //(node:8910) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
```
Is that bug or what?

**Comment by Zaedus** [comment]
My best guess is you're not waiting for the deletion of the project and are trying to undelete something that hasn't been deleted yet.

**Comment by iMrDJAi** [comment]
> 
> 
> My best guess is you're not waiting for the deletion of the project and are trying to undelete something that hasn't been deleted yet.

Nope, when the project is not deleted, the error will be different.
If I'm wrong, can you give me a working example? I kinda found that one in the Docs.
